web:
  build: cloudpebble/
  ports:
    - "80:80"
  volumes:
    - "./cloudpebble/:/code"
  links:
    - redis
    - postgres
    - s3
    - qemu
    - ycmd
  environment:
    - DEBUG="no"
    - RUN_WEB="yes"
    - AWS_ENABLED="yes"
    - PORT=80
    - AWS_S3_FAKE_S3=192.168.0.113:8003
    - MEDIA_URL=http://192.168.0.113:8003/builds.cloudpebble.net/
    - QEMU_URLS=http://192.168.0.113:8001/
    - YCM_URLS=http://192.168.0.113:8002/
    - PUBLIC_URL=http://192.168.0.113/
celery:
  build: cloudpebble/
  volumes:
    - "./cloudpebble/:/code"
  links:
    - redis
    - postgres
    - s3
  environment:
    - DEBUG="yes"
    - RUN_CELERY="yes"
    - AWS_ENABLED=yes
    - EXPORT_ROOT=http://192.168.0.113:8003/export.cloudpebble.net/
    - AWS_S3_FAKE_S3=192.168.0.113:8003
qemu:
  build: cloudpebble-qemu-controller/
  volumes:
    - "./cloudpebble-qemu-controller/:/code"
  ports:
    - "8001:80"
ycmd:
  build: cloudpebble-ycmd-proxy/
  volumes:
    - "./cloudpebble-ycmd-proxy/:/code"
  ports:
    - "8002:80"
redis:
  image: redis
postgres:
  image: postgres
s3:
  image: lphoward/fake-s3
  ports:
    - "8003:4569"
